<a href="https://colab.research.google.com/github/sejinseo/Itwill_Python/blob/main/ml09_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix

# 이진 분류(Binary Class Classification)

* scikit-learn 패키지의 breast cancer 예제 데이터 셋을 로딩.
* 악성종양(malignant)/양성종양(benign): 진짜 암/암이 아닌 종양을 분류하는 이진 분류 문제.
* 3가지 머신 러닝 분류 모델을 비교
    * KNN
    * Logistic Regression
    * SGD

In [140]:
# 데이터 셋 로드, 컬럼 확인
df = load_breast_cancer()
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [141]:
# 데이터 정보 확인
print(df['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [142]:
df['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [143]:
df['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [144]:
X = df['data'] #> 특성들의 (569, 30) shape의 2차원 배열
y = df['target'] #> 레이블 (569,) shape의 1차원 배열

In [145]:
X.shape, y.shape

((569, 30), (569,))

In [146]:
# 훈련 셋, 테스트 셋 분리
# 층화 추출
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                    stratify=y, random_state=42)

In [147]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

In [148]:
y_train.shape, y_test.shape

((455,), (114,))

In [149]:
# 사용할 모델 생성, KNN 알고리즘 사용
scaler = StandardScaler()
clf = KNeighborsClassifier()
model = Pipeline(steps=[('scaler', scaler), ('clf', clf)])

In [150]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('clf', KNeighborsClassifier())])

In [151]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred[:5])

[1 0 1 1 1]


In [152]:
# 훈련 셋 실젯값
print(y_train[:5])

[1 0 1 1 1]


In [153]:
print(confusion_matrix(y_train, train_pred))

[[161   9]
 [  3 282]]


In [154]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       170
           1       0.97      0.99      0.98       285

    accuracy                           0.97       455
   macro avg       0.98      0.97      0.97       455
weighted avg       0.97      0.97      0.97       455



In [155]:
# 훈련셋 정확도
model.score(X_train, y_train)

0.9736263736263736

In [156]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1
 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [157]:
# 테스트 셋 실제값
print(y_test)

[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [158]:
print(confusion_matrix(y_test, test_pred))

[[39  3]
 [ 2 70]]


In [159]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [160]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.956140350877193

In [161]:
# 모델 생성, LogisticRegression() 사용
scaler = StandardScaler()
log_reg = LogisticRegression()
model = Pipeline(steps=[('scaler', scaler), ('log_reg', log_reg)])

In [162]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('log_reg', LogisticRegression())])

In [163]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred[:5])

[1 0 1 1 1]


In [164]:
# 훈련 셋 실젯값
print(y_train[:5])

[1 0 1 1 1]


In [165]:
print(confusion_matrix(y_train, train_pred))

[[166   4]
 [  1 284]]


In [166]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       170
           1       0.99      1.00      0.99       285

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455



In [167]:
# 훈련 셋 정확도
model.score(X_train, y_train)

0.989010989010989

In [168]:
# 훈련 셋 예측값
model.predict_proba(X_train[:5, :])

array([[5.01807816e-05, 9.99949819e-01],
       [9.99993900e-01, 6.10034062e-06],
       [6.24151801e-06, 9.99993758e-01],
       [1.00037401e-02, 9.89996260e-01],
       [7.79592815e-04, 9.99220407e-01]])

In [169]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [170]:
# 테스트 셋 실젯값
print(y_test)

[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [171]:
print(confusion_matrix(y_test, test_pred))

[[41  1]
 [ 1 71]]


In [172]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



In [173]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.9824561403508771

In [174]:
# 모델 생성
scaler = StandardScaler()
clf = SGDClassifier(loss='log', random_state=42) #> 선형 회귀식을 logistic 함수에 전달하기 위해서 loss= log
model = Pipeline(steps=[('scaler', scaler), ('clf', clf)])

In [175]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf', SGDClassifier(loss='log', random_state=42))])

In [176]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred[:10])

[1 0 1 1 1 1 1 1 1 1]


In [177]:
# 훈련 셋 실젯값
print(y_train[:10])

[1 0 1 1 1 1 1 1 1 1]


In [178]:
print(confusion_matrix(y_train, train_pred))

[[164   6]
 [  6 279]]


In [179]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       170
           1       0.98      0.98      0.98       285

    accuracy                           0.97       455
   macro avg       0.97      0.97      0.97       455
weighted avg       0.97      0.97      0.97       455



In [180]:
model.predict_proba(X_train[:5])

array([[0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.67616989e-49],
       [0.00000000e+00, 1.00000000e+00],
       [3.33066907e-15, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00]])

In [181]:
# 훈련 셋 정확도
model.score(X_train, y_train)

0.9736263736263736

In [182]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [183]:
# 테스트 셋 실젯값
print(y_test)

[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]


In [184]:
print(confusion_matrix(y_test, test_pred))

[[41  1]
 [ 2 70]]


In [185]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96        42
           1       0.99      0.97      0.98        72

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [186]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.9736842105263158

# 다중 클래스 분류(Multi-class Classification)

* scikit-learn 패키지의 iris 예제 데이터 셋을 로딩
* setosa/versicolor/virginca: 3개 클래스를 갖는 분류 문제.
* 3가지 머신 러닝 분류 모델 비교

In [187]:
# 데이터 셋 로드
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [188]:
X = iris.data # 속성
y = iris.target # 타겟

In [189]:
X.shape, y.shape # 속성 (150, 4) 2차원 배열, 타겟 (150,) 1차원 배열

((150, 4), (150,))

In [190]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [191]:
# 훈련 셋, 테스트 셋 분리
# 층화추출 사용
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    stratify=y, random_state=42)

In [230]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [231]:
y_train.shape, y_test.shape

((120,), (30,))

In [192]:
# 모델 생성
scaler = StandardScaler()
clf = KNeighborsClassifier()
model = Pipeline(steps=[('scaler', scaler), ('clf', clf)])

In [193]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('clf', KNeighborsClassifier())])

In [194]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred)

[0 1 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 1 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 2 1 2 1 1 2 0 0 0 1
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]


In [195]:
# 훈련 셋 실젯값
print(y_train)

[0 2 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 1 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 1 1 2 1 1 2 0 0 0 2
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]


In [196]:
print(confusion_matrix(y_train, train_pred))

[[40  0  0]
 [ 0 39  1]
 [ 0  2 38]]


In [197]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.95      0.97      0.96        40
           2       0.97      0.95      0.96        40

    accuracy                           0.97       120
   macro avg       0.98      0.97      0.97       120
weighted avg       0.98      0.97      0.97       120



In [198]:
# 훈련 셋 정확도
model.score(X_train, y_train)

0.975

In [199]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 1 0 2 1 1 2 1 1 0 2 0]


In [200]:
# 테스트 셋 실젯값
print(y_test)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]


In [201]:
print(confusion_matrix(y_test, test_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]


In [202]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [203]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.9333333333333333

In [204]:
# 모델 생성
scaler = StandardScaler()
clf = LogisticRegression()
model = Pipeline(steps=[('scaler', scaler), ('clf', clf)])

In [205]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('clf', LogisticRegression())])

In [206]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred)

[0 1 1 0 1 2 1 1 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 2 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 2 1 2 1 1 2 0 0 0 1
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]


In [207]:
# 훈련 셋 실젯값
print(y_train)

[0 2 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 1 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 1 1 2 1 1 2 0 0 0 2
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]


In [208]:
print(confusion_matrix(y_train, train_pred))

[[40  0  0]
 [ 0 38  2]
 [ 0  3 37]]


In [209]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.95      0.94        40
           2       0.95      0.93      0.94        40

    accuracy                           0.96       120
   macro avg       0.96      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120



In [210]:
# 훈련 셋 정확도
model.score(X_train, y_train)

0.9583333333333334

In [211]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 1 2 2 1 0 2 0]


In [212]:
# 테스트 셋 실젯값
print(y_test)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]


In [213]:
print(confusion_matrix(y_test, test_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


In [214]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [215]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.9333333333333333

In [216]:
# 모델 생성
scaler = StandardScaler()
clf = SGDClassifier(loss='log', random_state=42) #> 선형 회귀식을 logistic 함수에 전달하기 위해서 loss= log
model = Pipeline(steps=[('scaler', scaler), ('clf', clf)])

In [217]:
# 모델 훈련
model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('clf', SGDClassifier(loss='log', random_state=42))])

In [218]:
# 훈련 셋 예측값
train_pred = model.predict(X_train)
print(train_pred)

[0 2 2 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 2 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 2 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 2 1 2 1 2 2 0 0 0 2
 1 2 1 2 2 1 0 2 2 0 2 0 2 1 1 0 1 2 0 0 2 2 2 2 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 2 0]


In [219]:
# 훈련 셋 실젯값
print(y_train)

[0 2 1 0 1 2 1 2 2 2 2 1 1 1 1 0 0 2 2 0 1 0 2 0 1 2 2 0 2 0 0 1 1 0 2 2 1
 1 2 1 0 1 0 2 0 0 2 0 0 0 0 1 2 1 0 2 1 2 0 2 0 1 2 0 1 1 2 1 1 2 0 0 0 2
 1 2 1 2 2 1 0 2 1 0 2 0 2 1 1 0 1 2 0 0 2 2 2 1 2 0 2 1 2 2 0 1 1 1 1 1 0
 2 1 1 0 0 0 0 1 0]


In [220]:
print(confusion_matrix(y_train, train_pred))

[[40  0  0]
 [ 0 32  8]
 [ 0  0 40]]


In [221]:
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.80      0.89        40
           2       0.83      1.00      0.91        40

    accuracy                           0.93       120
   macro avg       0.94      0.93      0.93       120
weighted avg       0.94      0.93      0.93       120



In [222]:
# 훈련 셋 정확도
model.score(X_train, y_train)

0.9333333333333333

In [223]:
# 테스트 셋 예측값
test_pred = model.predict(X_test)
print(test_pred)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]


In [224]:
# 테스트 셋 실젯값
print(y_test)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]


In [225]:
print(confusion_matrix(y_test, test_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [227]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [228]:
# 테스트 셋 정확도
model.score(X_test, y_test)

0.9666666666666667