<a href="https://colab.research.google.com/github/sejinseo/Python/blob/main/py18_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석에 많이 사용되는 패키지

* NumPy: 다차원 배열(n-dimensional array)을 다루는 패키지. 머신 러닝(machine learning)에서 중요하게 사용됨.
* pandas: 데이터프레임(DataFrame)과 시리즈(Series)를 다루는 패키지. 데이터 분석에서 기본으로 사용되는 패키지.
* matplotlib: 데이터 시각화(그래프).

Google Colab은 데이터 분석과 머신 러닝에 필요한 대부분의 패키지들이 이미 설치되어 있음.

In [3]:
import numpy as np
import pandas as pd
import matplotlib

In [6]:
# Google Colab에 설치된 패키지 버전
print('NumPy version:', np.__version__)
print('pandas version:', pd.__version__)
print('matplotlib version:', matplotlib.__version__)

NumPy version: 1.21.5
pandas version: 1.3.5
matplotlib version: 3.2.2


# Python list

* 여러개의 값들을 저장할 수 있는 데이터 타입.
* 인덱스를 기반으로 값들을 저장하는 데이터 타입.
    * indexing: 인덱스로 원하는 위치의 값을 참조.
    * slicing: `[start, end)` 인덱스 범위의 값들로 이루어진 부분집합(list)을 만듦.
* `list + list`: extend 메서드의 기능. 두 개의 리스트를 이어붙여서 하나의 리스트를 만듦.
    ```
    [1, 2] + [3, 4] = [1, 2, 3, 4]
    ```
* `list * int, int * list`: list의 원소들을 정수 개수만큼 반복해서 추가.
    ```
    [1, 2] * 3 = [1, 2, 1, 2, 1, 2]
    3 * [1, 2] = [1, 2, 1, 2, 1, 2]
    ```

In [7]:
num_list1 = [1, 2, 3]
num_list2 = [10, 20, 30]

In [8]:
# indexing
print(num_list1[0])
print(num_list1[-1])

1
3


In [10]:
print(num_list1[:2])
print(num_list1[-2:])

[1, 2]
[2, 3]


In [11]:
num_list1 + num_list2

[1, 2, 3, 10, 20, 30]

In [12]:
2 * num_list1

[1, 2, 3, 1, 2, 3]

In [16]:
# num_list1과 num_list2의 같은 인덱스의 원소들끼리의 합을 원소로 갖는 리스트
# add_list = []
# for x, y in zip(num_list1, num_list2):
#     add_list.append(x + y)
add_list = [x + y for x, y in zip(num_list1, num_list2)]
add_list

[11, 22, 33]

In [20]:
# num_list1의 모든 원소에 곱하기 2를 한 결과
[2 * x for x in num_list1]

[2, 4, 6]

# NumPy(Numerical Python)

* 배열(array)을 쉽고 빠르게 연산(+, -, *, /, ...)하기 위한 라이브러리.
* NumPy 패키지의 대부분의 기능(함수, 메서드)들은 반복문의 기능을 가지고 있음.
* `np.ndarray` 클래스: NumPy 패키지의 기본 데이터 타입. n차원 배열(n-dimensional array).
    * ndarray는 같은 인덱스의 원소들끼리(element-wise) 연산을 수행함.

In [23]:
num_arr1 = np.array(num_list1) # np.array(): 객체를 ndarray 타입으로 변환.

In [25]:
num_arr1 # 식(exprssion) 출력 - ndarray.__repr__() 메서드의 리턴값을 출력

array([1, 2, 3])

In [27]:
print(num_arr1) # print() 함수는 ndarray.__str__() 메서드의 리턴값을 출력

[1 2 3]


In [28]:
type(num_arr1)

numpy.ndarray

In [31]:
num_arr2 = np.array(num_list2)
print(num_arr2)

[10 20 30]


In [34]:
# ndarray의 사칙연산 - element-wise operation
print(num_arr1 + num_arr2) 
print(num_arr1 - num_arr2)
print(num_arr1 * num_arr2)
print(num_arr1 / num_arr2)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


In [35]:
print(num_arr1 * 2)

[2 4 6]


In [40]:
# ndarray의 속성들(attributes)
print(num_arr1)
print('ndim =', num_arr1.ndim) # 차원(dimension)
print('size =', num_arr1.size) # ndarray의 크기(원소의 갯수)
print('shape =', num_arr1.shape) # 각 차원에서의 원소의 갯수
print('dtype =', num_arr1.dtype) # 원소의 데이터 타입

[1 2 3]
ndim = 1
size = 3
shape = (3,)
dtype = int64


* Python 숫자 타입
    * 정수: int
    * 실수: float
* np의 숫자 타입
    * 정수: int8, int16, int32, int64, ...
    * 실수: float16, float32, float64, ...

## 2차원 ndarray

In [41]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [42]:
print('ndim =', arr_2d.ndim)
print('size =', arr_2d.size)
print('shape =', arr_2d.shape)
print('dtype =', arr_2d.dtype)

ndim = 2
size = 6
shape = (2, 3)
dtype = int64


# np.ndarray 객체 생성 함수

```
np.array(object)
```
* object: 배열과 비슷한 객체들(리스트, 튜플, dict, ndarray, ...)

In [45]:
# 0 이상 10 이하의 짝수들로 이루어진 ndarray
evens = np.array([2 * x for x in range(6)])
print(evens)

[ 0  2  4  6  8 10]


```
np.arange(start, end, step)
```

* `range(start, end, step)` 함수의 사용 방법과 동일
* 1차원 배열 생성

In [46]:
evens = np.arange(0, 11, 2)
print(evens)

[ 0  2  4  6  8 10]


```
np.reshape(array, shape) 함수
np.ndarray.reshape(shape) 메서드
```



In [48]:
arr = np.arange(12)
print(arr) # (12, ) shape의 1차원 배열

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
# 함수 호출
np.reshape(arr, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# 메서드 호출
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# 함수(메서드) 연쇄 호출
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

```
np.random.rand(d0, d1, d2, ...) 함수
```

* `[0, 1)` 범위의 균등분포를 따르는 난수들로 만들어진 ndarray를 생성.
* `d0, d1, d2, ...`: ndarray에서 각 차원의 원소의 개수

In [60]:
np.random.rand(5) # (5,) shape의 1차원 배열

array([0.8800377 , 0.6518775 , 0.1664339 , 0.75766597, 0.96348773])

In [61]:
# (3, 4) shape의 2차원 배열
np.random.rand(3, 4)

array([[0.27370089, 0.8960339 , 0.42927841, 0.18308823],
       [0.87487535, 0.59140456, 0.23217789, 0.81144187],
       [0.82885061, 0.1087241 , 0.87314971, 0.72793471]])

```
np.random.randn(d0, d1, d2, ...) 함수
```

* 평균이 0이고 표준편차가 1인 표준정규분포(standard normal distribution)를 따르는 난수들의 배열을 생성.
* `d0, d1, d2, ...`: ndarray의 각 차원의 원소의 개수.

In [62]:
np.random.randn(5)

array([-0.7758178 , -1.06057694,  1.6771232 , -0.53826644, -0.06140303])

In [63]:
np.random.randn(3, 4)

array([[ 0.58085207,  0.60434094, -0.81224586,  1.5357347 ],
       [ 0.03722211, -2.05563299,  0.78001923,  1.29840904],
       [ 1.34822385, -0.80500634,  0.43821339, -0.57218826]])

```
np.random.randint(low, high, size, dtype) 함수
```

* `[low, high)` 범위의 균등분포를 따르는 정수 난수들의 배열 생성.
* `size`: ndarray의 모양(shape). 정수 또는 정수들의 tuple.
* `dtype`: int8, int16, int32, int64, ...

In [65]:
# 0 이상 10 미만의 정수 난수 5개로 이루어진 리스트
np.random.randint(0, 10, 5)

array([0, 3, 7, 1, 7])

In [66]:
np.random.randint(0, 10, size=(3, 4))

array([[6, 1, 3, 9],
       [6, 2, 7, 3],
       [1, 3, 3, 5]])